const LearningVocabulary = [
    { word: "Mann", article: "der", meaning: "man" },
    { word: "Vater", article: "der", meaning: "father" },
    { word: "Freund", article: "der", meaning: "friend" },
    { word: "Junge", article: "der", meaning: "boy" },
    { word: "Lehrer", article: "der", meaning: "teacher" },
    { word: "Arzt", article: "der", meaning: "doctor" },
    { word: "Name", article: "der", meaning: "name" },
    { word: "Tisch", article: "der", meaning: "table" },
    { word: "Stuhl", article: "der", meaning: "chair" },
    { word: "Hund", article: "der", meaning: "dog" },
    
    { word: "Tag", article: "der", meaning: "day" },
    { word: "Monat", article: "der", meaning: "month" },
    { word: "Bus", article: "der", meaning: "bus" },
    { word: "Zug", article: "der", meaning: "train" },
    { word: "Bahnhof", article: "der", meaning: "train station" },
    { word: "Apfel", article: "der", meaning: "apple" },
    { word: "Kaffee", article: "der", meaning: "coffee" },
    { word: "Tee", article: "der", meaning: "tea" },
    { word: "Kuchen", article: "der", meaning: "cake" },
    { word: "Film", article: "der", meaning: "movie" },

    { word: "Computer", article: "der", meaning: "computer" },
    { word: "Brief", article: "der", meaning: "letter" },
    { word: "Beruf", article: "der", meaning: "profession" },
    { word: "Kollege", article: "der", meaning: "colleague" },
    { word: "Schüler", article: "der", meaning: "student" },
    { word: "Schlüssel", article: "der", meaning: "key" },
    { word: "Schuh", article: "der", meaning: "shoe" },
    { word: "Fisch", article: "der", meaning: "fish" },
    { word: "Markt", article: "der", meaning: "market" },
    { word: "Onkel", article: "der", meaning: "uncle" },
    
    { word: "Frau", article: "die", meaning: "woman" },
    { word: "Mutter", article: "die", meaning: "mother" },
    { word: "Freundin", article: "die", meaning: "friend" },
    { word: "Lehrerin", article: "die", meaning: "teacher" },
    { word: "Ärztin", article: "die", meaning: "doctor" },
    { word: "Familie", article: "die", meaning: "family" },
    { word: "Schule", article: "die", meaning: "school" },
    { word: "Straße", article: "die", meaning: "street" },
    { word: "Lampe", article: "die", meaning: "lamp" },
    { word: "Zeitung", article: "die", meaning: "newspaper" },
    
    { word: "Tasche", article: "die", meaning: "bag" },
    { word: "Uhr", article: "die", meaning: "clock" },
    { word: "Tür", article: "die", meaning: "door" },
    { word: "Wohnung", article: "die", meaning: "apartment" },
    { word: "Küche", article: "die", meaning: "kitchen" },
    { word: "Banane", article: "die", meaning: "banana" },
    { word: "Tomate", article: "die", meaning: "tomato" },
    { word: "Butter", article: "die", meaning: "butter" },
    { word: "Milch", article: "die", meaning: "milk" },
    { word: "Sprache", article: "die", meaning: "language" },
    
    { word: "Arbeit", article: "die", meaning: "work" },
    { word: "Stadt", article: "die", meaning: "city" },
    { word: "Frage", article: "die", meaning: "question" },
    { word: "Antwort", article: "die", meaning: "answer" },
    { word: "Nummer", article: "die", meaning: "number" },
    { word: "Musik", article: "die", meaning: "music" },
    { word: "Polizei", article: "die", meaning: "police" },
    { word: "Blume", article: "die", meaning: "flower" },
    { word: "Jacke", article: "die", meaning: "jacket" },
    { word: "Schwester", article: "die", meaning: "sister" },
    
    { word: "Kind", article: "das", meaning: "child" },
    { word: "Haus", article: "das", meaning: "house" },
    { word: "Auto", article: "das", meaning: "car" },
    { word: "Buch", article: "das", meaning: "book" },
    { word: "Heft", article: "das", meaning: "notebook" },
    { word: "Bild", article: "das", meaning: "picture" },
    { word: "Zimmer", article: "das", meaning: "room" },
    { word: "Fenster", article: "das", meaning: "window" },
    { word: "Essen", article: "das", meaning: "food" },
    { word: "Brot", article: "das", meaning: "bread" },
    
    { word: "Ei", article: "das", meaning: "egg" },
    { word: "Wasser", article: "das", meaning: "water" },
    { word: "Bier", article: "das", meaning: "beer" },
    { word: "Telefon", article: "das", meaning: "telephone" },
    { word: "Handy", article: "das", meaning: "mobile phone" },
    { word: "Radio", article: "das", meaning: "radio" },
    { word: "Lied", article: "das", meaning: "song" },
    { word: "Jahr", article: "das", meaning: "year" },
    { word: "Problem", article: "das", meaning: "problem" },
    { word: "Geschenk", article: "das", meaning: "gift" },
    
    { word: "Hobby", article: "das", meaning: "hobby" },
    { word: "Frühstück", article: "das", meaning: "breakfast" },
    { word: "Gemüse", article: "das", meaning: "vegetable" },
    { word: "Fleisch", article: "das", meaning: "meat" },
    { word: "Tier", article: "das", meaning: "animal" },
    { word: "Bett", article: "das", meaning: "bed" },
    { word: "Spiel", article: "das", meaning: "game" },
    { word: "Kino", article: "das", meaning: "cinema" },
    { word: "Baby", article: "das", meaning: "baby" },
    { word: "Internet", article: "das", meaning: "internet" },

    { word: "Student", article: "der", meaning: "university student" },
    { word: "Kellner", article: "der", meaning: "waiter" },
    { word: "Nachbar", article: "der", meaning: "neighbor" },
    { word: "Vogel", article: "der", meaning: "bird" },
    { word: "Bleistift", article: "der", meaning: "pencil" },
    { word: "Kugelschreiber", article: "der", meaning: "ballpoint pen" },
    { word: "Rechner", article: "der", meaning: "calculator" },
    { word: "Kalender", article: "der", meaning: "calendar" },
    { word: "Löffel", article: "der", meaning: "spoon" },
    { word: "Bäcker", article: "der", meaning: "baker" },
  
    { word: "Freizeit", article: "die", meaning: "free time" },
    { word: "Woche", article: "die", meaning: "week" },
    { word: "Rechnung", article: "die", meaning: "bill" },
    { word: "Bluse", article: "die", meaning: "blouse" },
    { word: "Tochter", article: "die", meaning: "daughter" },
    { word: "Tante", article: "die", meaning: "aunt" },
    { word: "Universität", article: "die", meaning: "university" },
    { word: "Brille", article: "die", meaning: "glasses" },
    { word: "Post", article: "die", meaning: "post office/mail" },
    { word: "U-Bahn", article: "die", meaning: "subway" },
  
    { word: "Pizza", article: "die", meaning: "pizza" },
    { word: "Wurst", article: "die", meaning: "sausage" },
    { word: "Reise", article: "die", meaning: "trip" },
    { word: "Seite", article: "die", meaning: "page" },
    { word: "Welt", article: "die", meaning: "world" },
    { word: "Treppe", article: "die", meaning: "stairs" },
    { word: "Gruppe", article: "die", meaning: "group" },
    { word: "Geschichte", article: "die", meaning: "story/history" },
    { word: "Adresse", article: "die", meaning: "address" },
    { word: "Farbe", article: "die", meaning: "color" },
  
    { word: "Mädchen", article: "das", meaning: "girl" },
    { word: "Kleid", article: "das", meaning: "dress" },
    { word: "Gesicht", article: "das", meaning: "face" },
    { word: "Auge", article: "das", meaning: "eye" },
    { word: "Ohr", article: "das", meaning: "ear" },
    { word: "Bein", article: "das", meaning: "leg" },
    { word: "Hemd", article: "das", meaning: "shirt" },
    { word: "Fensterbrett", article: "das", meaning: "windowsill" },
    { word: "Konto", article: "das", meaning: "account" },
    { word: "Licht", article: "das", meaning: "light" },
  
    { word: "Büro", article: "das", meaning: "office" },
    { word: "Theater", article: "das", meaning: "theater" },
    { word: "Museum", article: "das", meaning: "museum" },
    { word: "Bad", article: "das", meaning: "bathroom" },
    { word: "Hotel", article: "das", meaning: "hotel" },
    { word: "Krankenhaus", article: "das", meaning: "hospital" },
    { word: "Dach", article: "das", meaning: "roof" },
    { word: "Leben", article: "das", meaning: "life" },
    { word: "Wörterbuch", article: "das", meaning: "dictionary" },
    { word: "Beispiel", article: "das", meaning: "example" },
  
    { word: "Kunde", article: "der", meaning: "customer" },
    { word: "Besuch", article: "der", meaning: "visit" },
    { word: "Schrank", article: "der", meaning: "cabinet" },
    { word: "Sohn", article: "der", meaning: "son" },
    { word: "Gast", article: "der", meaning: "guest" },
    { word: "Flughafen", article: "der", meaning: "airport" },
    { word: "Berg", article: "der", meaning: "mountain" },
    { word: "Wind", article: "der", meaning: "wind" },
    { word: "Boden", article: "der", meaning: "floor" },
    { word: "Winter", article: "der", meaning: "winter" },

    { word: "Entwickler", article: "der", meaning: "developer" },
    { word: "Laptop", article: "der", meaning: "laptop" },
    { word: "Drucker", article: "der", meaning: "printer" },
    { word: "Monitor", article: "der", meaning: "monitor" },
    { word: "Server", article: "der", meaning: "server" },
    { word: "Tastatur", article: "die", meaning: "keyboard" },
    { word: "Datei", article: "die", meaning: "file" },
    { word: "Programm", article: "das", meaning: "program" },
    { word: "System", article: "das", meaning: "system" },
    { word: "Maus", article: "die", meaning: "mouse" },

    // Daily Life & House
    { word: "Spiegel", article: "der", meaning: "mirror" },
    { word: "Regal", article: "das", meaning: "shelf" },
    { word: "Teppich", article: "der", meaning: "carpet" },
    { word: "Decke", article: "die", meaning: "ceiling/blanket" },
    { word: "Vorhang", article: "der", meaning: "curtain" },

    // Time & Activities
    { word: "Termin", article: "der", meaning: "appointment" },
    { word: "Urlaub", article: "der", meaning: "vacation" },
    { word: "Pause", article: "die", meaning: "break" },
    { word: "Alltag", article: "der", meaning: "everyday life" },
    { word: "Erinnerung", article: "die", meaning: "memory" },

    // Relationships & Emotions
    { word: "Chef", article: "der", meaning: "boss" },
    { word: "Beziehung", article: "die", meaning: "relationship" },
    { word: "Streit", article: "der", meaning: "argument" },
    { word: "Meinung", article: "die", meaning: "opinion" },
    { word: "Entscheidung", article: "die", meaning: "decision" },

    // Work & Communication
    { word: "Bewerbung", article: "die", meaning: "application" },
    { word: "Gespräch", article: "das", meaning: "conversation/interview" },
    { word: "Vertrag", article: "der", meaning: "contract" },
    { word: "Erfahrung", article: "die", meaning: "experience" },
    { word: "Möglichkeit", article: "die", meaning: "possibility" },

    // Abstract Concepts
    { word: "Ziel", article: "das", meaning: "goal" },
    { word: "Zukunft", article: "die", meaning: "future" },
    { word: "Angst", article: "die", meaning: "fear" },
    { word: "Fehler", article: "der", meaning: "mistake" },
    { word: "Glück", article: "das", meaning: "luck/happiness" },

    // Tech & Digital
    { word: "Netzwerk", article: "das", meaning: "network" },
    { word: "Passwort", article: "das", meaning: "password" },
    { word: "Webseite", article: "die", meaning: "website" },
    { word: "Zugang", article: "der", meaning: "access" },
];
